services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    environment:
      - LARAVEL_DOMAIN=${LARAVEL_DOMAIN}
      - FASTAPI_DOMAIN=${FASTAPI_DOMAIN}
    volumes:
      - nginx-certs:/etc/nginx/certs
      - laravel-public:/var/www/html/public
    depends_on:
      laravel:
        condition: service_healthy
      fastapi:
        condition: service_started
    networks:
      - leanpublic

  laravel:
    build: ./laravel
    restart: on-failure
    volumes:
      - laravel-storage:/var/www/html/storage
      - laravel-public:/var/www/html/public
    healthcheck:
      test: ["CMD-SHELL", "php artisan migrate:status | grep -q '2026_06_20_212256_add_github_id_to_users_table' || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 15s
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - leanpublic

  fastapi:
    build: ./fastapi
    env_file:
      - ./fastapi/.env
    depends_on:
      laravel:
        condition: service_healthy
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - leanpublic

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - leanpublic

  redis:
    image: redis:7-alpine
    networks:
      - leanpublic

volumes:
  laravel-storage:
  mysql-data:
  nginx-certs:
  laravel-public:
networks:
  leanpublic:
